In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [ ]:
#pip install sodapy

In [ ]:
#pip install dnspython

In [ ]:
#pip install pymongo

In [15]:
#pip install pymongo[srv]

In [2]:
import pandas as pd
from sodapy import Socrata

# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("data.kcmo.org", None)

# Example authenticated client (needed for non-public datasets):
# client = Socrata(data.kcmo.org,
#                  MyAppToken,
#                  username="user@example.com",
#                  password="AFakePassword")

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
#result_1 = client.get("dmjw-d28i", limit=200000)
#result_2 = client.get("pxaa-ahcm", limit=200000)
#result_3 = client.get("vsgj-uufz", limit=200000)
#result_4 = client.get("w795-ffu6", limit=200000)
#result_5 = client.get("x39y-7d3m", limit=200000)


# Convert to pandas DataFrame
#results_df_2018 = pd.DataFrame.from_records(result_1)
#results_df_2019 = pd.DataFrame.from_records(result_2)
#results_df_2020 = pd.DataFrame.from_records(result_3)
#results_df_2021 = pd.DataFrame.from_records(result_4)
#results_df_2022 = pd.DataFrame.from_records(result_5)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [48]:
#results_df_2018=results_df_2018.rename(columns={":@computed_region_kk66_ngf4": "computed_region_kk66_ngf4", ":@computed_region_9t2m_phkm": "computed_region_9t2m_phkm",":@computed_region_my34_vmp8":"computed_region_my34_vmp8",":@computed_region_w4hf_t6bp":"computed_region_w4hf_t6bp"})
#results_df_2019=results_df_2019.rename(columns={":@computed_region_kk66_ngf4": "computed_region_kk66_ngf4", ":@computed_region_9t2m_phkm": "computed_region_9t2m_phkm",":@computed_region_my34_vmp8":"computed_region_my34_vmp8",":@computed_region_w4hf_t6bp":"computed_region_w4hf_t6bp"})
#results_df_2020=results_df_2020.rename(columns={":@computed_region_kk66_ngf4": "computed_region_kk66_ngf4", ":@computed_region_9t2m_phkm": "computed_region_9t2m_phkm",":@computed_region_my34_vmp8":"computed_region_my34_vmp8",":@computed_region_w4hf_t6bp":"computed_region_w4hf_t6bp"})
#results_df_2021=results_df_2021.rename(columns={":@computed_region_kk66_ngf4": "computed_region_kk66_ngf4", ":@computed_region_9t2m_phkm": "computed_region_9t2m_phkm",":@computed_region_my34_vmp8":"computed_region_my34_vmp8",":@computed_region_w4hf_t6bp":"computed_region_w4hf_t6bp"})
#results_df_2022=results_df_2022.rename(columns={":@computed_region_kk66_ngf4": "computed_region_kk66_ngf4", ":@computed_region_9t2m_phkm": "computed_region_9t2m_phkm",":@computed_region_my34_vmp8":"computed_region_my34_vmp8",":@computed_region_w4hf_t6bp":"computed_region_w4hf_t6bp"})

In [3]:
import pymongo
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

# USERNAME,PASSWORD FOR MONGO DB

In [7]:
client = pymongo.MongoClient("mongodb+srv://username:password@cluster0.2kfd1pw.mongodb.net/?retryWrites=true&w=majority", server_api=ServerApi('1'))
db=client.get_database('Kansas')

In [79]:
#db["crime_record_2018"].insert_many(results_df_2018.to_dict('records'))
#db["crime_record_2019"].insert_many(results_df_2019.to_dict('records'))
#db["crime_record_2020"].insert_many(results_df_2020.to_dict('records'))
#db["crime_record_2021"].insert_many(results_df_2021.to_dict('records'))
#db["crime_record_2022"].insert_many(results_df_2022.to_dict('records'))

In [5]:
satir_sayisi_bilgi=db.crime_record_2018
satir_sayisi_bilgi.count_documents({})

128938

# DICTIONARY FROM MONGO DB TO DF

In [6]:
from pymongo import MongoClient
db = client.get_database('Kansas')
#########################################3
collection_2018 = db["crime_record_2018"]
data = collection_2018.find()
df_18=pd.DataFrame.from_dict(data)

In [109]:
collection_2019 = db["crime_record_2019"]
data = collection_2019.find()
df_19=pd.DataFrame.from_dict(data)

In [111]:
collection_2020 = db["crime_record_2020"]
data = collection_2020.find()
df_20=pd.DataFrame.from_dict(data)

In [112]:
collection_2021 = db["crime_record_2021"]
data = collection_2021.find()
df_21=pd.DataFrame.from_dict(data)

In [113]:
collection_2022 = db["crime_record_2022"]
data = collection_2022.find()
df_22=pd.DataFrame.from_dict(data)

In [8]:
df_18.head()

,_id,report_no,reported_date,reported_time,from_date,from_time,to_date,to_time,offense,ibrs,...,involvement,firearm_used_flag,location,race,sex,age,computed_region_kk66_ngf4,computed_region_9t2m_phkm,computed_region_my34_vmp8,computed_region_w4hf_t6bp
0,63bdfc7ec5f54698ce86ab63,180038631,2018-05-23T00:00:00.000,10:37,2018-01-01T00:00:00.000,15:00,2018-05-22T00:00:00.000,16:15,690,23H,...,VIC,N,"{'human_address': '{""address"": ""4200 SCOTT RD""...",W,M,74,NaN,NaN,NaN,NaN
1,63bdfc7ec5f54698ce86ab61,180039506,2018-05-26T00:00:00.000,01:00,2018-05-26T00:00:00.000,01:00,NaN,NaN,2655,90J,...,VIC,N,"{'latitude': '39.09961', 'longitude': '-94.583...",W,M,31,5,4,7,75
2,63bdfc7ec5f54698ce86ab82,180017912,2018-03-08T00:00:00.000,07:59,2018-02-23T00:00:00.000,17:30,2018-03-08T00:00:00.000,07:00,502,220,...,SUS,N,"{'latitude': '39.132702', 'longitude': '-94.50...",U,U,NaN,53,4,7,144
3,63bdfc7ec5f54698ce86abcb,180023774,2018-03-30T00:00:00.000,15:51,2018-03-30T00:00:00.000,15:38,NaN,NaN,630,23C,...,VIC,N,"{'human_address': '{""address"": ""8500 STATE LIN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,63bdfc7ec5f54698ce86abd8,180027697,2018-04-14T00:00:00.000,03:30,2018-04-13T00:00:00.000,23:51,NaN,NaN,101,09A,...,SUS,Y,"{'latitude': '39.001765', 'longitude': '-94.56...",B,M,NaN,96,2,7,151

In [114]:
df_19.head()

,_id,report_no,reported_date,reported_time,from_date,from_time,to_date,to_time,offense,ibrs,...,firearm_used_flag,race,sex,age,rep_dist,location,computed_region_kk66_ngf4,computed_region_9t2m_phkm,computed_region_my34_vmp8,computed_region_w4hf_t6bp
0,63bdff0ec5f54698ce88a308,KC19044451,2019-06-14T00:00:00.000,16:34,2019-06-14T00:00:00.000,16:30,2019-06-14T00:00:00.000,16:30,Stealing – Shoplift,23C,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,63bdff0ec5f54698ce88a309,KC19052276,2019-07-12T00:00:00.000,22:11,2019-07-13T00:00:00.000,2:28,NaN,NaN,City/Municipal Warrant Arrest,NaN,...,False,W,F,30,NaN,NaN,NaN,NaN,NaN,NaN
2,63bdff0ec5f54698ce88a30a,KC19071090,2019-09-17T00:00:00.000,13:26,2019-09-17T00:00:00.000,13:15,NaN,NaN,Stealing – Shoplift,23C,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,63bdff0ec5f54698ce88a30b,KC19073018,2019-09-24T00:00:00.000,7:32,2019-09-24T00:00:00.000,7:20,NaN,NaN,Abuse of a Child,13B,...,False,B,M,39,PJ6509,NaN,NaN,NaN,NaN,NaN
4,63bdff0ec5f54698ce88a30c,KC19076088,2019-10-04T00:00:00.000,13:59,2019-10-04T00:00:00.000,13:50,NaN,NaN,Recovered Stolen Auto,NaN,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [115]:
df_20.head()

,_id,report_no,reported_date,reported_time,from_date,from_time,offense,ibrs,description,beat,...,firearm_used_flag,to_date,to_time,rep_dist,age,location,computed_region_kk66_ngf4,computed_region_9t2m_phkm,computed_region_my34_vmp8,computed_region_w4hf_t6bp
0,63bdff5fc5f54698ce8a3864,KC20067792,2020-10-04T00:00:00.000,11:04,2020-10-03T00:00:00.000,18:00,Stealing – Other,23H,All Other Larceny,121,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,63bdff5fc5f54698ce8a3865,KC20017500,2020-03-08T00:00:00.000,19:24,2020-03-08T00:00:00.000,19:00,Stealing – Shoplift,90J,Trespass of Real Property,345,...,False,2020-03-08T00:00:00.000,19:00,PJ3601,NaN,NaN,NaN,NaN,NaN,NaN
2,63bdff5fc5f54698ce8a3866,KC20009823,2020-02-07T00:00:00.000,18:30,2020-02-07T00:00:00.000,18:01,Robbery (Armed Street),120,Robbery,542,...,True,NaN,NaN,PJ6554,NaN,NaN,NaN,NaN,NaN,NaN
3,63bdff5fc5f54698ce8a3867,KC20011191,2020-02-13T00:00:00.000,12:15,2020-02-13T00:00:00.000,12:15,Stealing – Shoplift,23C,Shoplifting,345,...,False,2020-02-13T00:00:00.000,12:15,PJ3601,37,NaN,NaN,NaN,NaN,NaN
4,63bdff5fc5f54698ce8a3868,KC20014727,2020-02-27T00:00:00.000,08:30,2020-01-12T00:00:00.000,16:35,Miscellaneous Investigation,NaN,NaN,344,...,False,NaN,NaN,PJ3281,38,NaN,NaN,NaN,NaN,NaN

In [116]:
df_21.head()

,_id,report_no,report_date,report_time,from_date,from_time,offense,ibrs,description,beat,...,firearmused_flag,age,age_range,to_date,to_time,location,:@computed_region_9t2m_phkm,:@computed_region_my34_vmp8,:@computed_region_w4hf_t6bp,:@computed_region_kk66_ngf4
0,63be049eeb7214537b1a4e80,KC21055624,2021-08-21T19:45:07.000,19:45,2021-08-21T19:45:00.000,19:45,Murder,09A,Murder,332,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,63be049eeb7214537b1a4e81,KC21012401,2021-02-24T11:35:29.000,11:35,2021-02-24T11:35:00.000,11:35,Stealing from Building/Residence,23D,Theft From Building,234,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,63be049eeb7214537b1a4e82,KC21017210,2021-03-17T15:46:42.000,15:46,2021-03-17T15:35:00.000,15:35,Assault (Aggravated),13A,Aggravated Assault,631,...,True,33,25-34,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,63be049eeb7214537b1a4e83,KC21005420,2021-01-25T11:18:00.000,11:18,2021-01-25T11:00:00.000,11:00,Recovered Stolen Auto,NaN,NaN,113,...,False,20,18-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,63be049eeb7214537b1a4e84,KC21010791,2021-02-17T11:41:39.000,11:41,2021-02-11T20:30:00.000,20:30,Stolen Auto,240,Motor Vehicle Theft,211,...,False,NaN,NaN,2021-02-11T20:45:00.000,20:45,NaN,NaN,NaN,NaN,NaN

In [117]:
df_22.head()

,_id,report_no,report_date,report_time,from_date,from_time,to_date,to_time,offense,ibrs,...,race,sex,age,firearmusedflag,location,age_range,:@computed_region_kk66_ngf4,:@computed_region_9t2m_phkm,:@computed_region_my34_vmp8,:@computed_region_w4hf_t6bp
0,63be0519eb7214537b1bb65f,KC22000029,2022-01-01T01:50:00.000,02:18,2022-01-01T01:50:00.000,01:50,2022-01-01T01:50:00.000,01:50,Assault (Aggravated),13B,...,B,M,23,False,"{'type': 'Point', 'coordinates': [-94.581, 39....",18-24,5,4,7,75
1,63be0519eb7214537b1bb660,KC22000197,2021-12-31T17:00:00.000,00:15,2021-12-31T17:00:00.000,17:00,2021-12-31T17:00:00.000,12:00,Rape - Statutory,11A,...,W,M,22,False,NaN,18-24,NaN,NaN,NaN,NaN
2,63be0519eb7214537b1bb661,KC22000585,2022-01-03T19:09:00.000,19:09,2022-01-03T19:09:00.000,19:09,2022-01-03T19:09:00.000,NaN,Miscellaneous Investigation,NaN,...,B,F,NaN,False,"{'type': 'Point', 'coordinates': [-94.57902, 3...",NaN,97,4,7,92
3,63be0519eb7214537b1bb662,KC22000642,2022-01-04T07:00:00.000,06:52,2022-01-04T07:00:00.000,07:00,2022-01-04T07:00:00.000,NaN,Recovered Stolen Auto,NaN,...,W,M,50,False,"{'type': 'Point', 'coordinates': [-94.56041, 3...",45-54,189,1,7,153
4,63be0519eb7214537b1bb663,KC22000666,2022-01-04T10:00:00.000,10:25,2022-01-04T10:00:00.000,10:00,2022-01-04T10:00:00.000,10:05,Stolen Auto,240,...,W,M,37,False,"{'type': 'Point', 'coordinates': [-94.44858, 3...",35-44,NaN,NaN,7,146

#### Specifying Categorical and Numerical Columns

#### Assign appropriate datatype

#### Descriptive Data Analysis

#### Detecting and Plotting NaN values

#### Plotting Numerical Columns